name: "CI"
on:
  pull_request:
  push:
jobs:
  macos:
    runs-on:
      - macos-latest
    steps:
    - name: Setup Repo
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Flake Check
      run: nix flake check
  linux:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Setup Repo
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Flake Check
      run: nix flake check
    - name: Build Bundle
      run: nix bundle
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./runmd-arx
  docker:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Setup Repo
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Create Docker Image
      run: nix bundle --bundler github:NixOS/bundlers#toDockerImage
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: |
        docker load -i ./runmd-0.0.1.tar.gz
        docker tag runmd-0.0.1:latest paolino/runmd:latest
        docker push paolino/runmd:latest
  report:
    runs-on: ubuntu-latest
    needs: [macos, linux, docker]
    if: always()
    steps:
    - name: pushover-actions
      uses: umahmood/pushover-actions@main
      env:
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
      with:
        status: ${{ job.status }}
        title: "CI Job Report"
        message: |
          macos: ${{ needs.macos.result }}
          linux: ${{ needs.linux.result }}
          docker: ${{ needs.docker.result }}
